### ISSUE TITLE
[Improvement] Cmd+Click to recursively fold/unfold nodes.

### ISSUE THREAD

**Issue by Akv2021** [markmap/markmap#171]
With a relatively large file, we want to toggle each "main" branch one by one, and then explore the sub-branches.
Right now the "Recursively toggle the next node" option turns off after a single click. 
And it takes effort/time to move the cursor back to turn it on, and back to the node we were working on. 

It would be much better user experience if cmd+click behaves as if the "Recursively toggle the next node" option were selected. This way we can fully fold/unfold selective nodes (by holding cmd key while clicking) while moving only single level (clicks without holding cmd key) for the rest. All without having to move back and forth to the toggle icon.

Would really appreciate if this can be achieved !

**Comment by innicio** [comment]
Dear gera2ld,
I am writing to request that you maintain both options in the Mindmap application. I understand that you have recently made changes that include a new function to expand and collapse nodes recursively by pressing the Ctrl key, but this option is not viable on mobile devices as they do not have this key on their virtual keyboard. On the other hand, the previous option of expanding and collapsing nodes recursively by tapping on the node is very useful for mobile device users, as it allows them to work more efficiently and quickly on complex projects with many nodes.
However, I also want to highlight that the new option of expanding and collapsing nodes recursively by pressing the Ctrl key is very useful for computer users, as it allows them to work more efficiently and quickly. Therefore, I request that you maintain both options so that users can choose the option that best suits their device and way of working.
Thank you for your attention to this matter, and I look forward to your response.
Sincerely,
Justo

**Comment by gera2ld** [comment]
Thanks for your suggestion, it sounds reasonable. I'll add the toggle back.

**Comment by Akv2021** [comment]
Hi @gera2ld,
Thank you very much for attending this, this will greatly affect the UX in large note files.
However in vscode extensions I see that the last release was in Feb. So will I need to wait for the release to try it out ?
```
Last released 2/7/2023, 18:26:32
Last updated 7/15/2023, 09:57:13
```

1. Post reading @innicio's comment I thought there's another way but could neither find the vsix file for markmap nor side-loading (manually copying to ~/.vscode/extensions/) worked. Am I missing something here ?
2. I was even more curious about it's usage on mobile devices. @innicio Were you talking about using extension in vscode.dev on mobile ?

Thanks again. Excited to try this and other recent commits soon.

**Comment by Akv2021** [comment]
Hi @gera2ld , 
Thanks for publishing the changes to vs code extension. 
However how do we use Ctrl Click feature on Mac ?
I tried the following on both vs code extension and demo website but could not use recursive toggle nodes behaviour :

1. Cmd (pressed) + Click -> Behaves same as normal click. Does not expand/collapse nodes recursively.
2. Cmd (press then release) + Click -> Same as normal click.
3. Ctrl (pressed OR press then release) + Click -> Opens right click menu (Cut/ Copy/ Paste in Vscode and Back/ Reload/ Inspect menu in Demo website.)

Please clarify.

**Comment by gera2ld** [comment]
@Akv2021 thanks for the report. I just learned that <kbd>Ctrl</kbd>+click is taken by the macOS system. I'll change it to <kbd>Cmd</kbd>+click instead (Approach 1).

**Comment by Akv2021** [comment]
@gera2ld ,
Thank you very much for the quick fix. 
I tried on demo website and it now works as expected.
Just waiting for the fix to roll out to vs code extension too !!

**Comment by harshvyas** [comment]
Would be great if the map could be navigated at all node levels using keyboard shortcuts only without any mouse clicks. Similar to https://www.mindmup.com/tutorials/keyboard.html navigation keys.
