### ISSUE TITLE
[feature-request] Support editing directly in markmap? And sync between markdown and markmap

### ISSUE THREAD

**Issue by donaldwuid** [markmap/markmap#238]
Current markmap is a readonly mindmap view of markdown.
Is it possible to support editing directly in markmap?
All modifications are sync bewteen the markdown and markmap.

why editing in markmap (mindmap)?
- it's more intuitive,
- it's more convinient to add sibling (enter key) and children (tab key) node
- it's much easier to fold/unfold.

why editing in mindmap and sync to markdown?
- markdown is the actual storage file of this mindmap
- it's (kinda) a public format
- beside viewed as mindmap, it can change to another view (via pandoc), e.g., pdf-like view, ppt-like view.

**Comment by gera2ld** [comment]
This is a good idea, but it's not feasible because the conversion from Markdown to Markmap is not lossless, and the two formats are not equivalent. So if we want to sync data from both sides, we can only support a subset of features, which doesn't seem like a good idea to me. Therefore, I prefer using Markmap as a rendering tool only, similar to Mermaid.
