### ISSUE TITLE
Is it possible to suppoer some of markdown grammar?

### ISSUE THREAD

**Issue by VincentSong915** [markmap/markmap#26]
Hi! Thank you for providing this fantastic program which did help me a lot on my study.

When I'm writing with markdown, I unconciously use those grammars to make my file look neater. Like using html label `<font>` to change face, color and size to emphasis the important. And also sometimes I need to add some graphs for easier understanding using`![graph](path)` .

I'm wondering if it is possible to support those features. If so, it would be great and powerful.

Thanks again for your contribution!

**Comment by gera2ld** [comment]
Raw HTML (e.g. `<font>...</font>`) is not supported because it is so flexible and unpredictable that may lead to incorrect node extraction. For example, it's hard to decide how the nodes wrapped in some raw HTML should be rendered.

As for graphs, do you mean to create graph nodes? I think I can expose an extensive way to extract nodes in the future.

**Comment by PhiLhoSoft** [comment]
Technically, it is not Markdown grammar, it is HTML, and an obsolete one! (`<font>` hand been deprecated for a long time).
Apparently, simple Markdown is supported, as show in the playground: `**inline** ~~text~~ *styles*` --> **inline** ~~text~~ *styles*

One note, though, to @gera2ld: you style the `<strong>` tag with a `font-weight: bolder;` style, but it goes from 300 to 400, and the difference is not visible, at least on Firefox and Chrome in Windows.
I suggest to use a simple `font-weight: bold;` instead.

**Comment by gera2ld** [comment]
HTML is already supported.
