### ISSUE TITLE
support render in node.js

### ISSUE THREAD

**Issue by seven1240** [markmap/markmap#86]
First thanks to the great mind and great software.

similar to https://github.com/gera2ld/markmap/issues/66 , I'd like to render to svg/png in node.js, but I tried jsdom and svg.js, all failed, maybe because they are not real DOMs.

seems markmap use d3.js, and d3.js seems support jsdom. anyway, render mindmap to svg doesn't need a real dom. is it possible to make it work in node.js ?

Thanks.

**Comment by gera2ld** [comment]
The closest solution is to use a headless browser like Puppeteer. See https://markmap.js.org/docs/guide--use-with-nodejs

The reason is that Markdown is so complex that it requires a browser engine to render everything properly. Only simple styleless text can be supported if we want to get rid of a browser.
